services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --explicit_defaults_for_timestamp=1
      --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - backend

  api:
    build:
      context: ./petshop
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-api
    env_file:
      - ./petshop/.env
    environment:
      TZ: ${TZ}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - backend
  
  frontend:
    build:
      context: ./petshop-front
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-front
    depends_on:
      api:
        condition: service_started
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./petshop-front:/app        
    networks:
      - backend
  

networks:
  backend:

volumes:
  db_data:
